version: '3'
services:
  api:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports:
      - '3010:3010'
    depends_on:
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo:27017/swapi-nest
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
